return {
	require("plugins.ui"),
	require("plugins.treesitter"),
	require("plugins.lsp"),
	require("plugins.cmp"),
	require("plugins.telescope"),
	require("plugins.whichkey"),
	require("plugins.neotree"),
	require("plugins.gitsigns"),
	require("plugins.bufferline"),
	require("plugins.autopairs"),
	require("plugins.indentscope"),
	require("plugins.indentline"),
	require("plugins.navic"),
}
